"""add query_cache table

Revision ID: c3d4e5f6a7b8
Revises: b2c3d4e5f6a7
Create Date: 2024-01-03 00:00:00.000000
"""

from __future__ import annotations

from typing import Sequence, Union
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

revision: str = "c3d4e5f6a7b8"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "query_cache",
        sa.Column("cache_key", sa.String(64), primary_key=True, nullable=False,
                  comment="SHA-256 of (connection_id + normalised question)"),
        sa.Column("connection_id", sa.String(36), nullable=False,
                  comment="UUID of the database connection that generated this result"),
        sa.Column("question", sa.Text(), nullable=False,
                  comment="Original natural-language question"),
        sa.Column("sql_query", sa.Text(), nullable=False,
                  comment="Validated SQL generated by the LLM"),
        sa.Column("sql_reasoning", sa.Text(), nullable=False, server_default="",
                  comment="LLM chain-of-thought reasoning for the SQL"),
        sa.Column("sql_confidence", sa.Float(), nullable=False, server_default="0.0",
                  comment="LLM self-reported confidence [0, 1]"),
        # Result metadata
        sa.Column("columns", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb"),
                  comment="List of column names"),
        sa.Column("row_count", sa.Integer(), nullable=False, server_default="0",
                  comment="Total rows returned by the query"),
        sa.Column("result_preview", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb"),
                  comment="First N rows of the result set (for cache hits)"),
        sa.Column("truncated", sa.Boolean(), nullable=False, server_default=sa.text("false"),
                  comment="True if the result set was truncated at max_rows"),
        sa.Column("execution_ms", sa.Float(), nullable=False, server_default="0.0",
                  comment="SQL execution time in milliseconds"),
        # Token usage
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("llm_model", sa.String(100), nullable=False, server_default=""),
        sa.Column("pipeline_ms", sa.Float(), nullable=False, server_default="0.0",
                  comment="Total pipeline execution time in milliseconds"),
        # Embedding
        sa.Column("embedding", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb"),
                  comment="384-dim float32 embedding vector as JSON array"),
        sa.Column("embedding_model", sa.String(100), nullable=False, server_default="",
                  comment="Embedding model used (e.g. all-MiniLM-L6-v2)"),
        # Cache management
        sa.Column("hit_count", sa.Integer(), nullable=False, server_default="0",
                  comment="Number of times this entry has been served from cache"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true"),
                  comment="False if this entry has been manually invalidated"),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False,
                  comment="Entry expires and will no longer be matched after this timestamp"),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False,
                  server_default=sa.text("now()")),
    )

    # Indexes for common access patterns
    op.create_index("ix_query_cache_connection_id", "query_cache", ["connection_id"])
    op.create_index("ix_query_cache_expires_at", "query_cache", ["expires_at"])
    op.create_index("ix_query_cache_is_active", "query_cache", ["is_active"])
    op.create_index(
        "ix_query_cache_connection_active",
        "query_cache",
        ["connection_id", "is_active", "expires_at"],
    )
    op.create_index(
        "ix_query_cache_hit_count",
        "query_cache",
        ["connection_id", "hit_count"],
    )


def downgrade() -> None:
    op.drop_index("ix_query_cache_hit_count", table_name="query_cache")
    op.drop_index("ix_query_cache_connection_active", table_name="query_cache")
    op.drop_index("ix_query_cache_is_active", table_name="query_cache")
    op.drop_index("ix_query_cache_expires_at", table_name="query_cache")
    op.drop_index("ix_query_cache_connection_id", table_name="query_cache")
    op.drop_table("query_cache")
